- lib/error-stuff.php
- lib/settings-stuff.php
- lib/stuff.php
I had to create by hand the option jurassic-ninja to
jurassic-ninja-settings
> Make the main menu item be the sites admin item

- lib/rest-api-stuff.php
- lib/stuff.php
Makes the addition of new features easier
> Make launch_wordpress accept an array of features instead of multiple arguments

- composer.json
- jurassic.ninja.php
- lib/cron-stuff.php
- lib/db-stuff.php
- lib/error-stuff.php
- lib/settings-stuff.php
- lib/stuff.php
- lib/views/sites.php
* c2a5f9b Make the JS only load on creating pages
* 68bf936 Add docs to some functions
* 5600af2 Rename table creation function
* 95349d8 Rename cron task callback
* 7918630 introduce page_is_launching_page
* 1c24992 rename to add_settings_page()
* d96b490 polish main plugin file with comments and ordering stuff
> More flyby changes

- .gitignore
- lib/stuff.php
> Features: Add ability to install and activate Woo

- jurassicninja.js
- lib/db-stuff.php
- lib/rest-api-stuff.php
- lib/settings-stuff.php
- lib/stuff.php
- lib/views/sites.php
visitin `/create?shortlived` will launch a site that lasts for an hour (configurable)
> Add ability to launch shortlived sites

- lib/stuff.php
A random number is appended to the subdomain
> Add more randomness to subdomain generation for shortlived sites.

- jurassicninja.js
- lib/rest-api-stuff.php
This functionality overrides the setting configured as default behaviour for the regular create endpoint.
> Add jetpack and nojetpack GET parameter support if the page including the JS carries them in the URL

- jurassicninja.js
- lib/rest-api-stuff.php
- lib/stuff.php
Makes the sites launched via `/create` run on PHP7.0 
Perfect timing...
> Default to PHP 7.0

- lib/cron-stuff.php
- lib/rest-api-stuff.php
- lib/stuff.php
Fixes #75
* Adds error handling when launching sites from the API
* Adds error handling when creating sysuser
* Adds error handling when purging sites
* Adds error handling when running commands on the freshly launched site
> Handle errors better

- jurassicninja.js
- lib/rest-api-stuff.php
- lib/stuff.php
* Introduces the filters:
* `jurassic_ninja_rest_create_request_features` for filtering the features requested through the `/create` endpoint.
* `jurassic_ninja_features_default_values` for adding new feature flags and default values for them.
* Introduces the `jurassic_ninja_add_features` action for being able to act on a requested feature.
* Refactors the js file to make more sense regarding names and code organization.
> Add filters and actions to allow for a more modular approach for feature addition

- jurassic.ninja.php
- lib/cron-stuff.php
- lib/db-stuff.php
> Run the purge cron task every fifteen minutes

- features/wp-downgrade.php
- features/wp-rollback.php
- jurassic.ninja.php
- lib/stuff.php
[WP Downgrade](https://wordpress.org/plugins/wp-downgrade/) adds the ability to install an old version of WordPress
>  Add ability to launch with wp-downgrade installed

- features/code-snippets.php
- features/gutenberg.php
- jurassic.ninja.php
- lib/stuff.php
* Add ability to launch with Code Snippets plugin
* Bumps version to 3.3.
> Add ability to launch sites with the Code Snippets plugin installed

- features/jetpack-beta.php
- jurassic.ninja.php
- lib/rest-api-stuff.php
* Fixes the forwarding of an error coming from jetpack-beta feature
* Bumps to version 3.3.3
> Fix the way an error is handled when requesting a feature

- changelog.md
- composer.json
- jurassic.ninja.php
* Bumps version to 3.6.1
* Updates changelog
> Bump to 3.6.1

- features/gutenberg.php
- features/multisite.php
- jurassic.ninja.php
*  Allow multisite from GET parameter
* Show proper error if both types of multisite are requested
* Add setting to have Gutenberg installed by default
> Allow Gutenberg to have a setting to be a default and Multisite as a GET parameter request

- features/woocommerce-beta-tester.php
- jurassic.ninja.php
- jurassicninja.js
- lib/rest-api-stuff.php
* Removes `/wp-json/jurassicninja/specialops/create` in favor of `/wp-json/jurassicninja/create`.
> REST API: Unify site launching endpoints.

- README.md
- jurassicninja.js
* Took in account e2e tests on Automattic/wp-e2e-tests depending on these elements so to not break them:
* Here where the [element is picked by id](https://github.com/Automattic/wp-e2e-tests/blob/3f1b8068f3f6185d5aa8169ec2a6e8af20881262/lib/pages/wporg-creator-page.js#L26).
* Here where the [link to the site is found by innerText](https://github.com/Automattic/wp-e2e-tests/blob/3f1b8068f3f6185d5aa8169ec2a6e8af20881262/lib/pages/wporg-creator-page.js#L22).
> Create Page: Move messages out of js into data attributes present in page's content.

- features/gutenpack.php
- jurassic.ninja.php
- lib/stuff.php
This is being run in production right now under [Jetpack 4.1 Beta 3](https://github.com/Automattic/jurassic.ninja/releases/tag/4.1-beta3) ...
> Add ability to build Gutenberg blocks for Jetpack from Calypso SDK

- features/plugins.php
- jurassic.ninja.php
1. Adds feature `classic-editor` for launching with the classic editor plugin installed
2. Bumps plugin version to 4.7
> Add ability to launch with Classic Editor plugin

- jurassic.ninja.php
- lib/words/nouns.txt
mas que un amigo! fuiste un hermano!
> add "chimuelo" to nouns list

- bin/build-gutenpack.sh
- jurassic.ninja.php
The commands for building gutenpack has changed.
> Update gutenpack build script again.

- jurassic.ninja.php
- jurassicninja.js
Some change was left out of #175 (not picking the features from text inputs)
> Fix Jetpack Beta branch picker

- jurassic.ninja.php
- jurassicninja.js
> Update auth error HTTP Status number for check in JavaScript  code

- features/ssl.php
- jurassic.ninja.php
- lib/cli-stuff.php
- lib/db-stuff.php
- lib/serverpilot-stuff.php
- lib/settings-stuff.php
- lib/stuff.php
- lib/views/sites.php
Adds ability to have a pool of pre-generated PHP environments to speed up launching of sites
Fixes #126 
Fixes #55
> Add ability to have a pool of pre-generated PHP environments

- jurassic.ninja.php
- lib/cli-stuff.php
- lib/serverpilot-stuff.php
- lib/stuff.php
* Limit purge to 1 site per run.
* Disable WP cron job. Do it via crontab
* Bumps versino to 5.0.1
> Fix PHP version update

- jurassic.ninja.php
- lib/stuff.php
- lib/views/sites.php
* Adds better app listing on the admin page
* Bumps version to 5.1
> Improve admin page

- composer.json
- jurassic.ninja.php
Current version does not work with composer v2 so `composer install` does not work
> Update dealerdirect-phpcodesniffer composer installer version

- docs/specialops.md
- jurassic.ninja.php
> Add support for PHP 8

- features/plugins.php
- jurassic.ninja.php
https://www.mailpoet.com/blog/mailpoet-joins-woocommerce/
https://wordpress.org/plugins/mailpoet/
> Add Mailpoet to plugins

- jurassic.ninja.php
Fixes mismatch between plugin header verision and latest release version
> Bump to 5.10.1

- docker-compose.yml
- docs/specialops.md
- features/jetpack-beta.php
- jurassic.ninja.php
- jurassicninja.js
Jetpack Beta plugin v3.0.0 adds the ability to work with multiple
plugins. This enhances Jurassic Ninja to take advantage of that,
offering to install a branch for each available plugin and then doing
so.
For this to fully work, you'll have to edit the specialops page with the
change included in this PR.
I managed to partially test this using the docker-compose file, at least the UI seems to work. I didn't have the ServerPilot plan to test actual launching.
~~Of course, don't merge and deploy this until after we actually release Jetpack Beta 3.0.0.~~ 3.0.0 has been released.
> Enhance for Jetpack Beta 3.0.0

- jurassicninja.js
In #239 I mistakenly assumed it was handling query parameters the way
PHP does. Since it doesn't, do something simpler to support sub-items.
> Fix collectFeaturesFromQueryString

- jurassic.ninja.php
> Bump version to 5.11.4

- composer.json
- features/jetpack-beta.php
- phpcs.xml
Adds declaration so CI doesn't fail out.
> Add Jetpack i18n declaration

- .gitignore
- features/plugins.php
- jurassic.ninja.php
Also
* Adds `.DS_Store to .gitignore`
* Bumps version to 5.19
> Add Jetpack VideoPress plugin to installable plugins

- jurassic.ninja.php
- lib/settings-stuff.php
Adds these versions to the `available_php_versions()` array
> Add support for PHP 8.0 and PHP 8.1
