- jurassic.ninja.php
The link was not rendered if on the fronted, because `plugins.php` is not always loaded
> Topbar: Use admin_url() instead of menu_page_url

- lib/stuff.php
Allows to install the [Debug plugin](https://wordpress.org/plugins/debug).
So, `WP_DEBUG` and `WP_DEBUG_LOG` can be enabled without the need for editing `wp-config.php` by hand
> Add feature 'debug' for installing the Debug plugin

- lib/stuff.php
Fixes #47 
This is needed if #45 is going to be implemented.
It's not desireable to end up with a subdomain like `stupid-pig` or `lazy-italian`, etc. I've gotten combinations like that and was embarrassed.
Will filter out combinations including any of these words:
```
'african',
'american',
'asian',
'australian',
'black',
'booby',
'british',
'chinese',
'cuban',
'dung',
'erect',
'eurasian',
'european',
'foolish',
'indian',
'italian',
'japanese',
'mexican',
'peruvian',
'southern',
'northern',
'sperm',
'stupid',
'sumatran',
'syrian',
```
> Filter out some probably offensive combinations of words for the subdomains

- lib/error-stuff.php
yeah, namespaces have no “namespace globals”. They’re just globals. And
wp-includes/widgets.php already defined a global $errors.
> Rename $errors to $jurassic_ninja_errors

- lib/settings-stuff.php
- lib/stuff.php
Fixes #45.
A site with domain prehistoric-persian.jurassic.ninja will have a WordPress title of "Prehistoric Ninja"
> Add setting to make launched sites have a site title related to their subdomain

- jurassicninja.js
- lib/stuff.php
Turned out that the `debug` plugin wasn't actually able to udpate wp-config.php
So, WP_DEBUG and WP_DEBUG_LOG can be enabled without the need for editing wp-config.php by hand
> Replace debug plugin for config-constants and wp-log-viewer plugins

- lib/settings-stuff.php
> Settings: avoid exception being thrown when options are not there yet

- jurassicninja.js
- lib/rest-api-stuff.php
- lib/stuff.php
Add possibility to install any jetpack branch during site creation. This would give a possibility to migrate jetpack related wp-e2e-tests to jurassic.ninja completely.
implemented: url options: `create/?jetpack-beta&branch=try/branch-name`
This PR relies on already merged functionalities in jetpack-beta plugin(https://github.com/Automattic/jetpack-beta/pull/42)
cc @oskosk
> Add possibility to install jetpack PR branch

- jurassicninja.js
- lib/rest-api-stuff.php
- lib/settings-stuff.php
... So we can have `/create?wp-debug-log`
> Add wp-debug-log GET parameter support and setting for enabling it by default

- jurassic.ninja.php
- lib/rest-api-stuff.php
- lib/serverpilot-stuff.php
- lib/settings-stuff.php
- lib/stuff.php
* Adds checkbox for enabling or disabling the launching with a custom certificate.
* Adds textareas for pasting Private Key and SSL certificate
* Renames feature `ssl` to `auto_ssl`.
* Blocks custom ssl feature for subdomain based multisite as regular wildcard certificates are not useful beyond the first subdomain.
* Blocks custom ssl if feature `auto_ssl` is also being requested. This should probably throw instead of just logging a debug message.
* **Bumps version to 2.1**
**Current issues**
1. [x] ~There's an error by which everytime a site with SSL is launched, everything breaks. 
nginx reports `failed (SSL: error:0906D066:PEM routines:PEM_read_bio:bad end line)`. When I get to see the cert file, it's stripped from the `----- END CERTIFICATE -----` line. Don't know at which level this …
> Add ability to launch sites with SSL

- features/wp-rollback.php
- lib/stuff.php
[WP Rollback](https://wordpress.org/plugins/wp-rollback/) adds the ability to install an old version of any plugin if
it's still on the Plugin Directory.
> Add ability to launch with wp-rollback installed

- jurassic.ninja.php
- lib/rest-api-stuff.php
- lib/serverpilot-stuff.php
- lib/stuff.php
* Renames the `runtime` parameter everywhere to be named `php_version` instead
* Randomizes the PHP version used for creating shortlived sites.
PHP-FPM receives USR1 after creating a new site or deleting one. This does not help keep the existing PHP FPM pools alive 
and every other usage of a site running a PHP version that gets restarted results in 503 errors.
> Mitigate issues with PHP-FPM not gracefully restarting when sent USR1 signal on ServerPilot

- features/woocommerce-beta-tester.php
- jurassic.ninja.php
- lib/rest-api-stuff.php
- lib/stuff.php
Requesting for a site with the WooCommerce Beta Tester feature will implicitly install WooCommerce. 
The WooCommerce Beta Tester plugin currently provides the ability to check the latest tagged version in the GitHub Repository for WooCommerce
https://github.com/woocommerce/woocommerce/tags
> Add ability to launch sites with the WooCommerce Beta Tester plugin installed

- features/logged-in-user-email-address.php
- jurassic.ninja.php
- lib/stuff.php
* Allows to Make the admin email address of the site be the user's if the user is logged in while launching a site
* Adds setting for this.
* Bumps version to 3.6
> Use the logged in user email address for the launched site

- features/wordpress-5-beta.php
- jurassic.ninja.php
- lib/stuff.php
* Introduces the feature `wordpress-5-beta` available from the Special Ops page and as a `GET` parameter to the Create Page.
* Bumps version to `4.2`
> Add ability to launch sites with latest beta release of WordPress 5.0

- features/gutenberg-master.php
- jurassic.ninja.php
- lib/stuff.php
* Adds the ability to launch with Gutenberg built from master via the paramter `?gutenberg-master`.
* Bumps plugin version to 4.4
> Add ability to launch with bleeding edge Gutenberg (master branch)

- features/gutenberg-nightly.php
- jurassic.ninja.php
- lib/stuff.php
Thanks to Daniel Bachhuber who creates nightly bundles of Gutenberg's master branch every six hours, we can now launch sites with `?gutenberg-nightly` and have an alpha version of Gutenberg available on the site as it's launched.
https://danielbachhuber.com/2018/10/02/gutenberg-nightly-build/
* Adds ability to launch a site with nightly Gutenberg via the `?gutenberg-nightly` parameter.
* Bumps plugin version to 4.5
> Add ability to launch with a nightly release of Gutenberg

- features/wordpress-4.php
- jurassic.ninja.php
- lib/stuff.php
When WordPress 5.0 is released, JN will launch sites with it. 
Asking Jurassic NInja to launch a site with the feature `wordpress-4` will create a site and install WordPress 4 on it
> Add ability to launch with latest stable WordPress 4

- features/gutenpack.php
- jurassic.ninja.php
This feature broke when the branch of #147 was deleted as the path pointed to the branch and not master.
* Fixes path
* Bumps plugin version to 4.7.2
> Fix Gutenpack script url path

- jurassic.ninja.php
- lib/serverpilot-stuff.php
- phpcs.xml
> Add PHP 7.3 to the version matrix for shortlived sites and make sites default to PHP 7.2

- features/content.php
- jurassic.ninja.php
- lib/stuff.php
Introduces the feature `content` so the site is launched with content.
This is a very basic and kickoff-like implementation, using sample content that I found on http://wptest.io/
Was about to drop the intent, but then realized that the dataset took Jetpack in account (creating galleries for battletesting "Tiled galleries") and actually suggests installing Jetpack.
> Add ability to launch with pregenerated content

- jurassic.ninja.php
- jurassicninja.js
This updates the favicon so that it includes a dot when building telling you the progress of the build.
Before:
After: 
Notice the dot. 
I wasn't able to fully test the change.
> Adds tab indicator to the build page

- features/plugins.php
- jurassic.ninja.php
* Adds the params are `crowdsignal`, `wp-super-cache`, `wp-job-manager`.
* Bumps to 4.12
> Add ability to launch a site with WP Job Manager, WP Super Cache, and /or Crowdsignal.

- jurassicninja.js
Fixes the function that is suppose to generate the favicon by making sure the the root path is being used. 
I tested this by running the function in the dev console and the result worked on the production. 
cc: @oskosk
> Faviocn: Make sure that we use the root relative url

- bin/build-gutenpack.sh
- jurassic.ninja.php
The commands to build gutenpack changed in Calypso.
This PR updates the commands and bumps version to 4.13.2
> Update the commands in the build-gutenpack.sh script 

- features/block-xmlrpc.php
- jurassic.ninja.php
- lib/stuff.php
It randomizes the technique used to block it. 
1. Adding instructions in `.htaccess` to deny access (http 403)
2. Removing `xmlrpc.php` (http 404).
> Add ability to launch a site with xmlrpc.php blocked from HTTP access

- features/ssl.php
- jurassic.ninja.php
ServerPilot stopped putting the magic calculation of a site's URL scheme in wp-config.php
```
define('SP_REQUEST_URL', ($_SERVER['HTTPS'] ? 'https://' : 'http://') . $_SERVER['HTTP_HOST']);
define('WP_SITEURL', SP_REQUEST_URL);
define('WP_HOME', SP_REQUEST_URL);
```
This PR makes sure we set the `siteurl` and `home` options after launching the site with SSL.
This was causing problems with Jetack's signature.
> Set home and siteurl options on launch for sites using SSL

- jurassic.ninja.php
- lib/stuff.php
ServerPilot stopped running `wp rewrite flush` and this leaves the site without an htaccess. 
This PR downloads a file and fixes behaviour for creating multistes but still not enough. Then runs `wp rewrite structure '/%year%/%monthnum%/%day%/%postname%/' and `wp rewrite flush`
> Add htaccess and run wp rewrite

- jurassic.ninja.php
- lib/serverpilot-stuff.php
Latest WordPress (5.2) bails on running over PHP versions earlier than 5.6 and the site health feature just recommends to upgrade to 7.3
> Remove old PHP versions and default to PHP 7.3

- features/jetpack-beta.php
- jurassic.ninja.php
Currently if we send an empty value in `branch` when `jetpack-beta` is requested, JN tries to match that empty value to available matches and fails to launch
> Check if the selected branch is not empty too for defaulting to master when jetpack-beta requested

- jurassic.ninja.php
- lib/stuff.php
This should help prevent automated scripts finding out about the site before the person launching it.
There have been cases of people reaching the site to find it locked down because some automated script visited it first.
> Stop pinging Ping-O-Matic on launch

- docs/specialops.md
- features/jetpack-debug-helper.php
- jurassic.ninja.php
- lib/stuff.php
By launching with `create/?jetpack-debug-helper&shortlived` you can have the [Jetpack Debug Helper](https://dev.jurassic.ninja/create/?jetpack-debug-helper&shortlived) installed and active.
* Bumps JN version to 5.6
* Upddates specialops.md to include the checkbox for Jetpack Debu Helper
> Add ability to install the jetpack debug helper plugin on launch

- features/jetpack-licensing.php
Jetpack Licensing now has a dedicated `/product-families` endpoint which returns all products that we can issue licenses for. This PR updates the Licensing integration of JN to read that endpoint instead of using hardcoded products.
How it works:
1. Products will now be fetched from the new API endpoint on every time you open up the SpecialOps page.
2. Successful responses will be stored as a fallback if the request in step 1 fails in the future.
> Jetpack Licensing: Use the new /product-families endpoint to fetch all possible products for licensing

- docs/specialops.md
- features/client-example.php
- features/jetpack-debug-helper.php
- jurassic.ninja.php
- lib/stuff.php
Client Example is a plugin often used to test and debug Jetpack connection: https://github.com/Automattic/client-example
This PR adds the plugin to the "specialops" page, so it could be automatically installed on the sites.
> Add ability to install Client Example plugin on launch

- features/jetpack-debug-helper.php
- jurassic.ninja.php
I accidentally overwritten some of the Jetpack Debug Helper initialization code in the "Client Example" PR: #212.
This PR is:
- fixing the problem (reverting that overwritten code)
- bumping the version number
> Bringing back the Jetpack Debug Helper

- README.md
For using JN, we don't need to tell people to install the dev dependencies.
> Readme: Do not install devdeps

- composer.json
- features/jetpack-licensing.php
- tests/lib/class-teststuff.php
Just a few items needed for composer to install it on PHP 8.
* Sets PHP version bounds.
* Updates to phpunit 7 or 8, instead of 6.
* Reworks the tests a bit to be happy.
* Use Brain/Monkey for mocks.
* Fix an error in the licensing code that slid through at some point.﻿
> Additional PHP 8 compat

- features/wc-smooth-generator.php
The main branch usted to be `master` but now is `trunk`
> Update main branch name in wc-smooth-generator download URL

- features/themes.php
- lib/stuff.php
With FSE coming to WordPress, it would be handy to have a FSE theme available easily. This would add a themes installer and allow the tt1-blocks theme to be installed.
- Add a themes feature
- Require themes.php
> Add theme installer

- features/woocommerce-beta-tester.php
- jurassic.ninja.php
https://github.com/woocommerce/woocommerce-beta-tester/archive/master.zip is returning a 404 for me but https://github.com/woocommerce/woocommerce-beta-tester/archive/refs/heads/trunk.zip works—which I copied from the "Download ZIP" option on the GitHub repo main page.
> Update woocommerce-beta-tester plugin url

- jurassic.ninja.php
- lib/jetpack-stuff.php
See #118
This would disconnect Jetpack with the JN site is being purged. To fully complete 118, it would need to cancel the plan. There isn't baked-in Jetpack-side functionality for that at this time.﻿
> Disconnect Jetpack on purge

- lib/stuff.php
> Update Jetpack Beta Tester plugin download URL to latest release instead of master

- jurassic.ninja.php
- lib/jetpack-stuff.php
#228 introduced a hook for disconnecting sites before purging them. It was released when [Jurassic Ninja 5.11](https://github.com/Automattic/jurassic.ninja/releases/tag/5.11) got deployed.
This handler was missing its argument count on the call to `add_action`. The symptom was that the cron job running `wp jn purge` every 10 minutes, crashed with.
``
Too few arguments to function jn\{closure}(), 1 passed in class-wp-hook.php on line 294 and exactly 2 expected in lib/jetpack-stuff.php:13
```
As a result of this, sites accumulated up to the point where the system user max count was reached today. (1000 sysusers)
> Fix jetpack site purging hook

- jurassic.ninja.php
- lib/jetpack-stuff.php
Jetpack's CLI now requires either `blog` or `user` for disconnecting a site. 
* Updates the command to `wp jetpack disconnect blog`
* Bumps plugin version to 5.11.3
> Update jetpack disconnect hook command

- features/wc-smooth-generator.php
As of WC Smooth Generator 1.0.3 we create a zip of the released version. This PR updates the feature install to use the 1.0.3 zip instead of downloading `trunk` and setting up with `composer`.
I've created an issue for Smooth Generator to [create a permanent archive location](https://github.com/woocommerce/wc-smooth-generator/issues/61) so your URL won't need to be updated with each new release.
> update smooth generator to install released zip

- README.md
- docker-compose.yml
As far as I can tell, the JN local dev setup is meant to work off of the JP Docker setup. Updating the paths in `docker-compose.yml` and having both repos sit under the same directory allowed `docker-compose up` to work for me.
> Update docker-compose.yml paths

- features/plugins.php
- features/woocommerce-payments.php
- lib/stuff.php
This PR adds 4 features to Jurassic Ninja, see below for an explanation of each feature and example usage.
This feature installs and activates the latest [WooCommerce Payments](https://wordpress.org/plugins/woocommerce-payments) plugin from WordPress.org.
Example use: `https://jurassic.ninja/create/?woocommerce-payments`
~~This feature builds, installs and activates the WooCommerce Payments plugin for a given [`woocommerce-payments`](https://github.com/Automattic/woocommerce-payments) branch.~~
~~This is useful for `woocommerce-payments` code review as the pull request reviewer can quickly spin up a fresh JN site and test the proposed changes in the PR.~~
~~Example use: `https://jurassic.ninja/create/?woocommerce-payments-branch=try/jurassic-ninja`~~
**Update:** This feature was removed …
> Add WooCommerce Payments features

- features/jetpack-beta.php
- jurassic.ninja.php
* Allows for things like https://jurassic.ninja/create/?jetpack-beta&nojetpack which currently leaves Jetpack master on
* Bumps version to 5.13
> Don't activate jetpack-dev if asked jetpack-beta but also nojetpack

- features/woocommerce-payments.php
A few WCPay features were added in #249.
Since then we received a report that these features were being added to JN sites even when not explicitly requested.
>Hi Chris it seems the Dev Tools is installed automatically even if the checkbox is unchecked, and it throws fatal when using PHP 5.6
This PR ensures that the WCPay features are only loaded when explicitly requested.
Please note that I wasn't able to test this in my local JN environment as it's not working at the moment.
I believe this approach will work as I essentially followed the convention in the [WooCommerce Smooth Generator feature](https://github.com/Automattic/jurassic.ninja/blob/master/features/wc-smooth-generator.php).
> Only load WCPay features when requested

- lib/rest-api-stuff.php
Previously, only admins could create sites. We don't want everyone with JN access to be an admin, so let's open it up a bit to any auth'd user.
> Allow all users to create

- jurassic.ninja.php
Follow-up to #257 which changed the logic for the regular Create page. /specialops was broken for all the people moved to editor via p9dueE-4WP-p2. 
Logged in users will be able to use /specialops
> Fix specialops page for non-admins

- features/wc-smooth-generator.php
This pulls in the latest version of the WC Smooth Generator plugin, which includes a bug fix to ensure that it can actually run correctly.
Duplicate of and closes #250
> Update WC Smooth Generator version

- features/jetpack-beta-blocks.php
- jurassic.ninja.php
- lib/stuff.php
Allows to launch site with `?create?jetpack-beta-blocks` thus setting the JETPACK_BETA_BLOCKS constant to true
> Add jetpack-beta-blocks feature

- docs/specialops.md
- features/plugins.php
- jurassic.ninja.php
- lib/stuff.php
Fixes #266 
Fixes #355
Removes all the references of WP Log Viewer plugin that are not maintained anymore. 
I've already cleaned up the "Special Ops" page.
> Remove all the references to wp-log-viewer plugin

- features/jetpack-crm.php
- lib/stuff.php
Resolves #268 - add support for prepopulated data in Jetpack CRM
This adds a few tweaks to the Jetpack CRM section to allow us to more quickly and easily test various scenarios.
If `jpcrm-populate-crm-data` or `jpcrm-populate-woo-data` features are selected, it installs our Jetpack CRM Sample Data Generator plugin and runs a relevant command to populate data. If WooCommerce is not selected, the Woo data populator option will not show.
Also, it adds a tweak to select the radio button associated with a given JPCRM install version.
> Resolves #268 - add support for prepopulated data in Jetpack CRM

- jurassic.ninja.php
I merged https://github.com/Automattic/jurassic.ninja/pull/271 bumping to 5.19, but then it turned out there was already a [release 5.19](https://github.com/Automattic/jurassic.ninja/releases/tag/5.19) pointing to trunk and 5.18.1.
So with 5.20 I'll synchronize by creating a new release 5.20.
(The only reason why this matters is for being able to rapidly understand what version of JN is running in prod in case there's a bug or regression live on JN)
> Bump version to 5.20

- composer.json
- features/woocommerce-beta-tester.php
- jurassic.ninja.php
- jurassicninja.js
Recently we added a feature in WooCommerce Beta Tester to install a WooCommerce plugin version from branches on the WooCommerce repository.
This is an integration with that feature allowing the creation of a Jurassic Ninja site with a specific branch of WooCommerce installed.
I have tested this on the dev instance.
> Add WooCommerce Beta Tester Live Branches Integration

- features/woocommerce-payments.php
The relevant code was added here https://github.com/Automattic/jurassic.ninja/pull/249
Originally, we used the private repo (`woocommerce-payments-dev-tools`), then we moved a separate public repo (`woocommerce-payments-dev-tools-ci`) - https://github.com/Automattic/jurassic.ninja/commit/3b902c0e
- Without regular update to the public repo https://github.com/Automattic/woocommerce-payments-dev-tools-ci, we face this issue https://github.com/Automattic/woocommerce-payments/issues/5032
- I suggest using the release asset to still expose the dev-tools zip file but without revealing details why we make changes. 
Also, this approach using the latest release is similar to: 
https://github.com/Automattic/jurassic.ninja/blob/a2f3ff28e299ba645c02777084fa6e0ba4cc3709/features/wc-smooth-generator.php …
> Use latest release asset for WCPay Dev Tools (public)

- jurassicninja.js
p1685350748192869/1684816055.228779-slack-C03CPM3UXDJ
This PR updates `getAvailableWooCommerceBetaBranches` function to include `master` (trunk) prop so that we can see the trunk branch in the WooCommerce Beta Tester Live Branches dropdown.
I've tested this in dev console on JN.
1. Go to JN
2. Open the dev console
3. Copy and paste the `getAvailableWooCommerceBetaBranches` function
4. Run `getAvailableWooCommerceBetaBranches().then(console.log)`
5. Should see the `trunk` item in the array.
> Include trunk branch in the WooCommerce Beta Tester dropdown

- jurassic.ninja.php
- lib/class-serverpilotprovisioner.php
We were currently picking item `0` of the array returned by `available_php_version`, now we get it from the settings
> Fix way to handle default php version

- features/plugins.php
- lib/stuff.php
Untested, but adds the option in the backend for the user switching plugin (need to add to the UI via jurassic.ninja if this is merged and to the Live Branches script) as well as default users in the other roles.
A cousin to this PR for the Jetpack Docker environment: https://github.com/Automattic/jetpack/pull/32633
> Add option for user switching plugin and add other default users

- jurassic.ninja.php
- lib/stuff.php
Fixes an error when tying to fetch the error message if db creation fails
> Change reference from $app to $db object for getting error message
